baseURL = "https://eeeee-engineer.github.io/"
theme = "netcrave"
googleAnalytics = ""

[module]
  [[Module.mounts]]
    source = "static/img"
    target = "static/img"
  [[Module.mounts]]
    source = "static/dl"
    target = "static/dl"
